- package-lock.json
- package.json
- src/color/icons.json
- src/size/icons.json
- src/size/scale.json
Adds new Step Out icon shape. Adds a new micro size scale.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._ 
-- Orion Design System Team
> feat: update support for icons, add support for new micro size scale

- README.md
- package-lock.json
- package.json
- scripts/config.json
When consuming design tokens within a modern JS project, it's nice to have access to the variables using ES6 modules.
To facilitate this, I added the `javascript/es6` format to the JS transform group in the styleDisctionary config.
Also, I ran `npm audit fix` to fix 185 dependency vulnerabilities and added `package-lock.json` to the release git files so that the package version bump is version controlled in the lock file.
-- Orion Design System Team
> feat: ship es6 token variables

- src/color/_classic/brand.json
- src/color/_deprecated/brand.json
- src/depth.json
- src/shadow.json
**Fixes:** #15 
Update tokens to address incorrect and missing values.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._ 
-- Orion Design System Team
> fix: #15 issue with missing and incorrect values

- README.md
- scripts/config.json
- src/color/_deprecated/background-button.json
- src/color/_deprecated/background.json
- src/color/_deprecated/base.json
- src/color/_deprecated/border.json
- src/color/_deprecated/brand.json
- src/color/_deprecated/font.json
- src/color/alert.json
- src/color/background.json
- src/color/base.json
- src/color/border.json
- src/color/brand.json
- src/color/icon.json
- src/color/text.json
- src/color/ui.json
- remove legacy UI color reference and replace with new Atlas value
- deprecate colors for new Gray options
- deprecate unnecessary color values for new state colors
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._ 
-- Orion Design System Team
> Address issues with color references

- README.md
- package-lock.json
- package.json
- packageScripts/postinstall.js
- scripts/config.json
- scripts/styleDictionary.js
This PR contains a new feature to support https://github.com/AlaskaAirlines/AuroDesignTokens/issues/18
This feature will output a new token type of `auro-rgb` that is a custom Style Dictionary transform 
allowing for the output of the token to only be the RGB values without the `rgb()` CSS function. 
This is to allow for the use of these values to be used with the CSS `rgba()` color function. 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this …
> Release #10

- .github/PULL_REQUEST_TEMPLATE.md
- docs/api.md
- package-lock.json
- package.json
- scripts/config.json
- src/animation.json
- src/asset/font.json
- src/breakpoint.json
- src/color/alert.json
- src/color/background.json
- src/color/base.json
- src/color/border.json
- src/color/brand.json
- src/color/icon.json
- src/color/text.json
- src/color/ui.json
- src/depth.json
- src/shadow.json
- src/size/radius.json
- src/size/scale.json
- src/size/unitless-scale.json
- src/text.json
**Fixes:** #36 
This PR updates the Auro Design Tokens to use a new set of brand-neutral colors as specified in Issue #36. 
See https://auro-tokens-36.surge.sh/ for all changes.
PR https://github.com/AlaskaAirlines/auro-badge/pull/6 has a dependency on this work being completed. 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._ 
> Brand neutral specs

- scripts/config.json
- scripts/styleDictionary.js
- templates/map-flat.template
Add SCSS token flat map to support dynamically referencing Auro token values. See https://github.com/AlaskaAirlines/WebCoreStyleSheets/issues/64.
- Generate new `SCSSVariablesMapFlat.scss` file containing `$auroTokens` variable
- Use custom `map-flat` formatter due to an [known issue](https://github.com/amzn/style-dictionary/issues/298)
Add support for SCSS map object of Auro tokens. Sass does not support dynamic variable names, see example below. To write a helper to use CSS custom properties with a fallback value, a map lets us build the variable expression and get the token value dynamically in a cleaner, tighter way.
```scss
// the trouble with dynamic variable names
$foo: 42px;
$bar: \$#{$foo};
// expected: $bar: 42px;
// actual: $bar: '$foo';
// use case
// what's currently possible …
```
> feat: add SCSS map of Auro tokens

- src/animation.json
- src/asset/font.json
- src/color/base.json
- src/depth.json
- src/shadow.json
- src/text.json
**Fixes:** #40 
This update addresses a z-index update where there was a collision between popovers and dialog experiences. 
This update also removes unused JSON keys.  …
> Update depth tokens and remove deprecated JSON keys

- src/color/brand.json
- src/color/tier.json
Added colors in this file: https://www.figma.com/file/TBMhIMVRMkufKnyxqGzrZO/Color-Explorations?node-id=8%3A1150
**Fixes:** #56  (issue, if applicable)
> feature: tier color tokens (#56)

- src/color/ui.json
Darkened hover color for accessibility.
**Fixes:** #66  (issue, if applicable)
Changed bkg-hover color to #000000 6% opacity.
> feat: darken bkg-hover color #66

- src/size/scale.json
- src/text.json
**Resolves:** #70
Added new XXS body type design token.
> feat: add new type token

- src/elevation.json
**Fixes:** #69
Added elevation tokens based on this Figma file: https://www.figma.com/file/BwHtOWIYLTiBIF2VVy6K9g/Auro-Elevation-%26-Shadows?node-id=407%3A8
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any …
> feat(release): add elevation tokens

- .github/CODEOWNERS
- src/color/text.json
Added `midnight-400` as a text color token for emphasis. This is to support designers who have been using/want to use a different header color.
**Fixes:** #83 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any …
> feat: add emphasis text color #83

- scripts/config-dark.json
- scripts/styleDictionary.js
- src/color-dark/alert.json
- src/color-dark/background.json
- src/color-dark/base.json
- src/color-dark/border.json
- src/color-dark/brand.json
- src/color-dark/icon.json
- src/color-dark/text.json
- src/color-dark/tier.json
- src/color-dark/ui.json
- src/color/border.json
- src/color/icon.json
- src/color/text.json
- src/color/tier.json
- src/color/ui.json
**Fixes:** #88 
* Separate the light and dark tokens into two directories
* Configure build to generate new token files for dark theme
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be …
> Create dark mode design token set

- src/color/alert.json
- src/color/border.json
- src/color/icon.json
- src/color/text.json
- src/color/tier.json
- src/color/ui.json
**Fixes:** #91 
Re-import the `on-dark` tokens that were in the original design token file in order to prevent any color issues for those using the original design token file.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this …
> re-import deprecated dark tokens

- README.md
- src/color/alert.json
- src/color/border.json
- src/color/icon.json
- src/color/text.json
- src/color/tier.json
- src/color/ui.json
**Fixes:** #96 
Add `reference` and `version` data to deprecated color tokens to allow for them to be added to the deprecated token list on the doc site.
AC:
- The `reference` data is currently listed as "n/a", pending the upcoming design token naming work.
- To verify these changes, use the JSON data generated in `dist/tokens/JSObject--deprecated.js` on a local version of the docsite and use the data to build out the token list in the `deprecated.js` file …
> fix(json): add reference and version data to tokens #96

- src/breakpoint.json
- src/grid-breakpoint.json
- src/grid-column.json
- src/grid-gutter.json
- src/grid-margin.json
**Fixes:** #106
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your …
> feat: new grid token values

- src/color/alert.json
**Fixes:** #100 
The bkg alert colors will be used for the auro toast.
> feat: add bkg alert color tokens #100

- src/color/alert.json
- src/color/border.json
- src/color/icon.json
- src/color/text.json
- src/color/tier.json
- src/color/ui.json
**Resolves:** #98, #102
This PR is restructured from this previous PR. 
https://github.com/AlaskaAirlines/AuroDesignTokens/pull/105
The scope of this PR is to address incorrectly deprecated tokens and update tokens as needed to address a name convention change. 
_Pull Requests will be evaluated by …
> Token updates

- .github/workflows/testPublish.yml
- .husky/pre-commit
- package-lock.json
- package.json
**Fixes:** #115 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your …
> Node18 support 

- .github/workflows/testPublish.yml
- .npmignore
- package-lock.json
- package.json
Changes to be committed:
modified:   .npmignore
modified:   package-lock.json
modified:   package.json
**Resolves:** #126 
Current 
npm notice === Tarball Details ===
npm notice name:          @alaskaairux/design-tokens
npm notice version:       3.15.5
npm notice filename:      alaskaairux-design-tokens-3.15.5.tgz
npm notice package size:  92.4 kB
npm notice unpacked size: 1.3 MB
npm notice shasum:        60cad4d07845950fd665cb802e2bcf0b4e6fa871
npm notice …
> Optimize build pipeline

- package-lock.json
- package.json
- src/color/background.json
- src/color/base.json
**Fixes:** #135 
added new token for a gradient against all backgrounds
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of …
> add new token for gradient

- scripts/config-excursion.json
- src/color/background.json
- src/themes/excursion/animation.json
- src/themes/excursion/asset/font.json
- src/themes/excursion/color/alert.json
- src/themes/excursion/color/base.json
- src/themes/excursion/color/border.json
- src/themes/excursion/color/brand.json
- src/themes/excursion/color/container.json
- src/themes/excursion/color/excursion.json
- src/themes/excursion/color/icon.json
- src/themes/excursion/color/text.json
- src/themes/excursion/color/tier.json
- src/themes/excursion/color/ui.json
- src/themes/excursion/comments.json
- src/themes/excursion/depth copy.json
- src/themes/excursion/elevation.json
- src/themes/excursion/grid-breakpoint.json
- src/themes/excursion/grid-column.json
- src/themes/excursion/grid-gutter.json
- src/themes/excursion/grid-margin.json
- src/themes/excursion/size/radius.json
- src/themes/excursion/size/scale.json
- src/themes/excursion/size/unitless-scale.json
- src/themes/excursion/text.json
**Resolves:** #151 
* Add all tier 1 and 2 excursion theme tokens
* Add `primary` naming convention to Auro classic `background` tier 2 tokens
*  This change was made to support the `excursion` theme which has `background-primary` and `background-secondary` tokens
_Pull Requests will be evaluated …
> Add all excursion tokens

- src/color/icon.json
**Resolves:** #162
Update the icon soccess token to have the correct value
> fix(iconSuccess): update icon success to use correct base color ##162

- src/color/utility.json
**Resolves:** #167 
Add `utility tokens` outline in this document:
https://alaskaair-my.sharepoint.com/:x:/p/june_lee/EeyDi0RTK5xEosX7r0KZ_7MB61j_rxpC3V9l_9M8zQEwRQ?e=53dICc&nav=MTVfezQ0RDZFMDU3LTI0MDEtRTU0QS05QjkyLTRFQ0IyOUJBRTNDRn0&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1717622438583&web=1
**By submitting this Pull Request, I confirm that my contribution is made under the terms of …
> Add utility tokens

- src/color/icon.json
**Resolves:** #170 
Add 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your …
> Add greyscale icon tokens

- .github/settings.yml
- .github/workflows/testPublish.yml
- package-lock.json
- package.json
Resolves AlaskaAirlines/auro-cli#37
> Downgrade Node.js version requirement to 20 in configuration files

- README.md
- scripts/transformCSS.mjs
- Update the `data-` selector from `aag-theme="aag-theme-xx"` to `data-aag-theme="aag-theme-xx"`
- Refactors the CSS transformation script to be more DRY & data-driven
- Adds `hawaiian-classic` theme to bundle script
- Updates README with Alaska Classic
Blocked by: https://github.com/AlaskaAirlines/AuroDesignTokens/pull/235
Unblocks: https://github.com/AlaskaAirlines/AuroDocsSite/pull/311 …
> feat: update data selector for transformCSS

- scripts/config-auro1.json
- scripts/config-auro2.json
- src/themes/alaska-classic/basic/color/fare-brand.json
- src/themes/auro-1/basic/color/fare-brand.json
**Update**
- Farebrand token update
**Fix**
- Update Sass prefix
> perf: token update

- scripts/styleDictionary.mjs
- scripts/transformCSS.mjs
- src/themes/alaska-classic/advanced/color/expandedWidget.json
- src/themes/alaska/advanced/color/expandedWidget.json
- src/themes/auro-1/advanced/color/expandedWidget.json
- src/themes/auro-2/advanced/color/expandedWidget.json
- src/themes/hawaiian/advanced/color/expandedWidget.json
- test/tokenConsistency.js
- Add new `expandedWidget.json` tokens to the Advanced files
- Use structured data to enable objects without CSS syntax
- Add custom composite gradient transform in Style Dictionary for handling multi-layer gradients
- Fix TypeScript errors with JSDoc type definitions and type assertions in `styleDictionary`, `tokenConsistency`, and `transformCSS` scripts
- Improve error handling in build and transform scripts
- Update `tokenConsistency` to skip private tokens and avoid nested value recursion
```
--ds-advanced-color-expanded-widget-background: linear-gradient(180deg, rgba(38, 32, 67, 0.65) 0%, rgba(38, 32, 67, 0) 65%), linear-gradient(90deg, #463c8f 25.8%, #ce0c88 100%);
```
Figma: https://www.figma.com/design/Wps4EWS9VgQ7QSTYDdSPwA/HA-Gradient?node-id=1-25&m=dev
Technical Research …
> feat: add expanded widget advanced tokens
